driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: freebsd-9.3
  - name: freebsd-10.3
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list: test::default
  - name: resources
    run_list: test::resources
