driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-27
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list: test::default
  - name: create
    run_list: test::create
  - name: remove
    run_list: test::remove
